name: "Common Setup"
runs:
  using: "composite"
  steps:
    - name: Install other dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: jq gojq
        version: 1.0
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
    - name: Install Python 3.12
      shell: bash
      run: uv python install 3.12
