name: "Common Setup"
runs:
  - name: Checkout the repository
    uses: actions/checkout@main
  - name: Install uv
    uses: astral-sh/setup-uv@v7
    with:
      enable-cache: true
  - name: Install Python 3.12
    run: uv python install 3.12
